spring:
  datasource:
    url: jdbc:mysql://1.2.3.4:3306/erupt-weixin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xxxxxx
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  hibernate:
    ddl-auto: update

erupt:
  # default path: /opt/erupt-attachment
  uploadPath: D:/erupt/pictures
  keepUploadFileName: false
